version: 2
jobs:
  build:
    working_directory: /usr/src/dotenv
    docker:
      - image: nimlang/nim
      - image: postgres:9.6-alpine
        environment:
          POSTGRES_USER: nayef
          POSTGRES_DB: pol
    steps:
      - checkout
      - run:
          name: test
          environment: 
            PGHOST : "localhost"
            PGDB : "pol"
            PGUSER : "nayef"
            PGPASS : ""
          command: |
            LD_LIBRARY_PATH=/usr/local/pgsql/lib
            apt-get update -y
            apt-get install postgresql-client -y
            nimble test 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build


